// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./basic.js')
  await import('./compat.js')
  await import('./diff.js')
  await import('./fuzz.js')
  await import('./fuzz-bad-cache.js')
  await import('./prefetch.js')
  await import('./tree.js')
  await import('./undo.js')

  test.resume()
}
