// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./basic.js')
  await import('./diff.js')
  await import('./fuzz.js')
  await import('./undo.js')
  await import('./compression.js')

  test.resume()
}
