// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @bee/tree-pointer
const encoding0 = {
  preencode (state, m) {
    c.uint.preencode(state, m.core)
    c.uint.preencode(state, m.seq)
    c.uint.preencode(state, m.offset)
  },
  encode (state, m) {
    c.uint.encode(state, m.core)
    c.uint.encode(state, m.seq)
    c.uint.encode(state, m.offset)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)

    return {
      core: r0,
      seq: r1,
      offset: r2
    }
  }
}

// @bee/block-pointer
const encoding1 = {
  preencode (state, m) {
    c.uint.preencode(state, m.core)
    c.uint.preencode(state, m.seq)
  },
  encode (state, m) {
    c.uint.encode(state, m.core)
    c.uint.encode(state, m.seq)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)

    return {
      core: r0,
      seq: r1
    }
  }
}

// @bee/tree.keys
const encoding2_0 = c.array(encoding0)
// @bee/tree.children
const encoding2_1 = encoding2_0

// @bee/tree
const encoding2 = {
  preencode (state, m) {
    encoding2_0.preencode(state, m.keys)
    encoding2_1.preencode(state, m.children)
  },
  encode (state, m) {
    encoding2_0.encode(state, m.keys)
    encoding2_1.encode(state, m.children)
  },
  decode (state) {
    const r0 = encoding2_0.decode(state)
    const r1 = encoding2_1.decode(state)

    return {
      keys: r0,
      children: r1
    }
  }
}

// @bee/data
const encoding3 = {
  preencode (state, m) {
    c.buffer.preencode(state, m.key)
    c.buffer.preencode(state, m.value)
  },
  encode (state, m) {
    c.buffer.encode(state, m.key)
    c.buffer.encode(state, m.value)
  },
  decode (state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)

    return {
      key: r0,
      value: r1
    }
  }
}

// @bee/block.tree
const encoding4_3 = c.array(encoding2)
// @bee/block.data
const encoding4_4 = c.array(encoding3)
// @bee/block.cores
const encoding4_5 = c.array(c.fixed32)

// @bee/block
const encoding4 = {
  preencode (state, m) {
    c.uint.preencode(state, m.type)
    c.uint.preencode(state, m.batch)
    c.uint.preencode(state, m.pointer)
    state.end++ // max flag is 4 so always one byte

    if (m.tree) encoding4_3.preencode(state, m.tree)
    if (m.data) encoding4_4.preencode(state, m.data)
    if (m.cores) encoding4_5.preencode(state, m.cores)
  },
  encode (state, m) {
    const flags =
      (m.tree ? 1 : 0) |
      (m.data ? 2 : 0) |
      (m.cores ? 4 : 0)

    c.uint.encode(state, m.type)
    c.uint.encode(state, m.batch)
    c.uint.encode(state, m.pointer)
    c.uint.encode(state, flags)

    if (m.tree) encoding4_3.encode(state, m.tree)
    if (m.data) encoding4_4.encode(state, m.data)
    if (m.cores) encoding4_5.encode(state, m.cores)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      type: r0,
      batch: r1,
      pointer: r2,
      tree: (flags & 1) !== 0 ? encoding4_3.decode(state) : null,
      data: (flags & 2) !== 0 ? encoding4_4.decode(state) : null,
      cores: (flags & 4) !== 0 ? encoding4_5.decode(state) : null
    }
  }
}

function setVersion (v) {
  version = v
}

function encode (name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode (name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum (name) {
  switch (name) {
    default: throw new Error('Enum not found ' + name)
  }
}

function getEncoding (name) {
  switch (name) {
    case '@bee/tree-pointer': return encoding0
    case '@bee/block-pointer': return encoding1
    case '@bee/tree': return encoding2
    case '@bee/data': return encoding3
    case '@bee/block': return encoding4
    default: throw new Error('Encoder not found ' + name)
  }
}

function getStruct (name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode (state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode (state, m) {
      version = v
      enc.encode(state, m)
    },
    decode (state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
