// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @bee/tree-pointer-0
const encoding0 = {
  preencode(state, m) {
    c.uint.preencode(state, m.core)
    c.uint.preencode(state, m.seq)
    c.uint.preencode(state, m.offset)
  },
  encode(state, m) {
    c.uint.encode(state, m.core)
    c.uint.encode(state, m.seq)
    c.uint.encode(state, m.offset)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)

    return {
      core: r0,
      seq: r1,
      offset: r2
    }
  }
}

// @bee/tree-pointer
const encoding1 = {
  preencode(state, m) {
    state.end++ // flags are fixed size

    if (m.core) c.uint.preencode(state, m.core)
    if (m.seq) c.uint.preencode(state, m.seq)
    if (m.offset) c.uint.preencode(state, m.offset)
  },
  encode(state, m) {
    const flags = (m.core ? 1 : 0) | (m.seq ? 2 : 0) | (m.offset ? 4 : 0)

    c.uint8.encode(state, flags)

    if (m.core) c.uint.encode(state, m.core)
    if (m.seq) c.uint.encode(state, m.seq)
    if (m.offset) c.uint.encode(state, m.offset)
  },
  decode(state) {
    const flags = c.uint8.decode(state)

    return {
      core: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      seq: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      offset: (flags & 4) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bee/tree-pointer (inline)
const encoding1_inline = {
  preencode(state, m) {
    if (m.core) c.uint.preencode(state, m.core)
    if (m.seq) c.uint.preencode(state, m.seq)
    if (m.offset) c.uint.preencode(state, m.offset)
  },
  encode(state, m) {
    if (m.core) c.uint.encode(state, m.core)
    if (m.seq) c.uint.encode(state, m.seq)
    if (m.offset) c.uint.encode(state, m.offset)
  },
  decode(state, inlining) {
    const flags = inlining

    return {
      core: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      seq: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      offset: (flags & 4) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bee/tree-delta
const encoding2 = {
  preencode(state, m) {
    state.end++ // flags are fixed size

    if (m.index) c.uint8.preencode(state, m.index)
    if (m.pointer) encoding1_inline.preencode(state, m.pointer)
  },
  encode(state, m) {
    let flags = (m.type & 7) | (m.index ? 8 : 0) | (m.pointer ? 16 : 0)
    if (m.pointer) {
      flags |= (m.pointer.core ? 32 : 0) | (m.pointer.seq ? 64 : 0) | (m.pointer.offset ? 128 : 0)
    }

    c.uint8.encode(state, flags)

    if (m.index) c.uint8.encode(state, m.index)
    if (m.pointer) encoding1_inline.encode(state, m.pointer)
  },
  decode(state) {
    const flags = c.uint8.decode(state)

    return {
      type: flags & 7,
      index: (flags & 8) !== 0 ? c.uint8.decode(state) : 0,
      pointer: (flags & 16) !== 0 ? encoding1_inline.decode(state, flags >>> 5) : null
    }
  }
}

// @bee/cohort
const encoding3 = c.array(encoding2)

// @bee/value-pointer
const encoding4 = {
  preencode(state, m) {
    state.end++ // flags are fixed size

    if (m.core) c.uint.preencode(state, m.core)
    if (m.seq) c.uint.preencode(state, m.seq)
    if (m.offset) c.uint.preencode(state, m.offset)
    if (m.split) c.uint.preencode(state, m.split)
  },
  encode(state, m) {
    const flags = (m.core ? 1 : 0) | (m.seq ? 2 : 0) | (m.offset ? 4 : 0) | (m.split ? 8 : 0)

    c.uint8.encode(state, flags)

    if (m.core) c.uint.encode(state, m.core)
    if (m.seq) c.uint.encode(state, m.seq)
    if (m.offset) c.uint.encode(state, m.offset)
    if (m.split) c.uint.encode(state, m.split)
  },
  decode(state) {
    const flags = c.uint8.decode(state)

    return {
      core: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      seq: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      offset: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      split: (flags & 8) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bee/value-pointer (inline)
const encoding4_inline = {
  preencode(state, m) {
    if (m.core) c.uint.preencode(state, m.core)
    if (m.seq) c.uint.preencode(state, m.seq)
    if (m.offset) c.uint.preencode(state, m.offset)
    if (m.split) c.uint.preencode(state, m.split)
  },
  encode(state, m) {
    if (m.core) c.uint.encode(state, m.core)
    if (m.seq) c.uint.encode(state, m.seq)
    if (m.offset) c.uint.encode(state, m.offset)
    if (m.split) c.uint.encode(state, m.split)
  },
  decode(state, inlining) {
    const flags = inlining

    return {
      core: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      seq: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      offset: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      split: (flags & 8) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bee/block-pointer
const encoding5 = {
  preencode(state, m) {
    c.uint.preencode(state, m.core)
    c.uint.preencode(state, m.seq)
  },
  encode(state, m) {
    c.uint.encode(state, m.core)
    c.uint.encode(state, m.seq)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)

    return {
      core: r0,
      seq: r1
    }
  }
}

// @bee/batch-pointer
const encoding6 = {
  preencode(state, m) {
    c.uint.preencode(state, m.start)
    c.uint.preencode(state, m.end)
  },
  encode(state, m) {
    c.uint.encode(state, m.start)
    c.uint.encode(state, m.end)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)

    return {
      start: r0,
      end: r1
    }
  }
}

// @bee/tree-0.keys
const encoding7_0 = c.array(encoding0)
// @bee/tree-0.children
const encoding7_1 = encoding7_0

// @bee/tree-0
const encoding7 = {
  preencode(state, m) {
    encoding7_0.preencode(state, m.keys)
    encoding7_1.preencode(state, m.children)
  },
  encode(state, m) {
    encoding7_0.encode(state, m.keys)
    encoding7_1.encode(state, m.children)
  },
  decode(state) {
    const r0 = encoding7_0.decode(state)
    const r1 = encoding7_1.decode(state)

    return {
      keys: r0,
      children: r1
    }
  }
}

// @bee/tree.keys
const encoding8_0 = encoding3
// @bee/tree.children
const encoding8_1 = encoding3

// @bee/tree
const encoding8 = {
  preencode(state, m) {
    encoding8_0.preencode(state, m.keys)
    encoding8_1.preencode(state, m.children)
  },
  encode(state, m) {
    encoding8_0.encode(state, m.keys)
    encoding8_1.encode(state, m.children)
  },
  decode(state) {
    const r0 = encoding8_0.decode(state)
    const r1 = encoding8_1.decode(state)

    return {
      keys: r0,
      children: r1
    }
  }
}

// @bee/data
const encoding9 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
    c.buffer.preencode(state, m.value)
  },
  encode(state, m) {
    c.buffer.encode(state, m.key)
    c.buffer.encode(state, m.value)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)

    return {
      key: r0,
      value: r1
    }
  }
}

// @bee/key
const encoding10 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
    state.end++ // flags are fixed size

    if (m.value) c.buffer.preencode(state, m.value)
    if (m.valuePointer) encoding4_inline.preencode(state, m.valuePointer)
  },
  encode(state, m) {
    let flags = (m.value ? 1 : 0) | (m.valuePointer ? 2 : 0)
    if (m.valuePointer) {
      flags |=
        (m.valuePointer.core ? 4 : 0) |
        (m.valuePointer.seq ? 8 : 0) |
        (m.valuePointer.offset ? 16 : 0) |
        (m.valuePointer.split ? 32 : 0)
    }

    c.buffer.encode(state, m.key)
    c.uint8.encode(state, flags)

    if (m.value) c.buffer.encode(state, m.value)
    if (m.valuePointer) encoding4_inline.encode(state, m.valuePointer)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const flags = c.uint8.decode(state)

    return {
      key: r0,
      value: (flags & 1) !== 0 ? c.buffer.decode(state) : null,
      valuePointer: (flags & 2) !== 0 ? encoding4_inline.decode(state, flags >>> 2) : null
    }
  }
}

// @bee/core
const encoding11 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
    state.end++ // flags are fixed size

    if (m.fork) c.uint.preencode(state, m.fork)
    if (m.length) c.uint.preencode(state, m.length)
    if (m.treeHash) c.fixed32.preencode(state, m.treeHash)
  },
  encode(state, m) {
    const flags = (m.fork ? 1 : 0) | (m.length ? 2 : 0) | (m.treeHash ? 4 : 0)

    c.fixed32.encode(state, m.key)
    c.uint8.encode(state, flags)

    if (m.fork) c.uint.encode(state, m.fork)
    if (m.length) c.uint.encode(state, m.length)
    if (m.treeHash) c.fixed32.encode(state, m.treeHash)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const flags = c.uint8.decode(state)

    return {
      key: r0,
      fork: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      length: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      treeHash: (flags & 4) !== 0 ? c.fixed32.decode(state) : null
    }
  }
}

// @bee/block-0.tree
const encoding12_4 = c.array(encoding7)
// @bee/block-0.data
const encoding12_5 = c.array(encoding9)
// @bee/block-0.cores
const encoding12_6 = c.array(encoding11)

// @bee/block-0
const encoding12 = {
  preencode(state, m) {
    c.uint.preencode(state, m.type)
    c.uint.preencode(state, m.checkpoint)
    encoding6.preencode(state, m.batch)
    state.end++ // max flag is 8 so always one byte

    if (m.previous) encoding5.preencode(state, m.previous)
    if (m.tree) encoding12_4.preencode(state, m.tree)
    if (m.data) encoding12_5.preencode(state, m.data)
    if (m.cores) encoding12_6.preencode(state, m.cores)
  },
  encode(state, m) {
    const flags = (m.previous ? 1 : 0) | (m.tree ? 2 : 0) | (m.data ? 4 : 0) | (m.cores ? 8 : 0)

    c.uint.encode(state, m.type)
    c.uint.encode(state, m.checkpoint)
    encoding6.encode(state, m.batch)
    c.uint.encode(state, flags)

    if (m.previous) encoding5.encode(state, m.previous)
    if (m.tree) encoding12_4.encode(state, m.tree)
    if (m.data) encoding12_5.encode(state, m.data)
    if (m.cores) encoding12_6.encode(state, m.cores)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = encoding6.decode(state)
    const flags = c.uint.decode(state)

    return {
      type: r0,
      checkpoint: r1,
      batch: r2,
      previous: (flags & 1) !== 0 ? encoding5.decode(state) : null,
      tree: (flags & 2) !== 0 ? encoding12_4.decode(state) : null,
      data: (flags & 4) !== 0 ? encoding12_5.decode(state) : null,
      cores: (flags & 8) !== 0 ? encoding12_6.decode(state) : null
    }
  }
}

// @bee/block-1.cores
const encoding13_4 = encoding12_6
// @bee/block-1.tree
const encoding13_5 = c.array(encoding8)
// @bee/block-1.keys
const encoding13_6 = c.array(encoding10)
// @bee/block-1.values
const encoding13_7 = c.array(c.buffer)
// @bee/block-1.cohorts
const encoding13_8 = c.array(encoding3)

// @bee/block-1
const encoding13 = {
  preencode(state, m) {
    c.uint.preencode(state, m.type)
    c.uint.preencode(state, m.checkpoint)
    encoding6.preencode(state, m.batch)
    state.end++ // max flag is 32 so always one byte

    if (m.previous) encoding5.preencode(state, m.previous)
    if (m.cores) encoding13_4.preencode(state, m.cores)
    if (m.tree) encoding13_5.preencode(state, m.tree)
    if (m.keys) encoding13_6.preencode(state, m.keys)
    if (m.values) encoding13_7.preencode(state, m.values)
    if (m.cohorts) encoding13_8.preencode(state, m.cohorts)
  },
  encode(state, m) {
    const flags =
      (m.previous ? 1 : 0) |
      (m.cores ? 2 : 0) |
      (m.tree ? 4 : 0) |
      (m.keys ? 8 : 0) |
      (m.values ? 16 : 0) |
      (m.cohorts ? 32 : 0)

    c.uint.encode(state, m.type)
    c.uint.encode(state, m.checkpoint)
    encoding6.encode(state, m.batch)
    c.uint.encode(state, flags)

    if (m.previous) encoding5.encode(state, m.previous)
    if (m.cores) encoding13_4.encode(state, m.cores)
    if (m.tree) encoding13_5.encode(state, m.tree)
    if (m.keys) encoding13_6.encode(state, m.keys)
    if (m.values) encoding13_7.encode(state, m.values)
    if (m.cohorts) encoding13_8.encode(state, m.cohorts)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = encoding6.decode(state)
    const flags = c.uint.decode(state)

    return {
      type: r0,
      checkpoint: r1,
      batch: r2,
      previous: (flags & 1) !== 0 ? encoding5.decode(state) : null,
      cores: (flags & 2) !== 0 ? encoding13_4.decode(state) : null,
      tree: (flags & 4) !== 0 ? encoding13_5.decode(state) : null,
      keys: (flags & 8) !== 0 ? encoding13_6.decode(state) : null,
      values: (flags & 16) !== 0 ? encoding13_7.decode(state) : null,
      cohorts: (flags & 32) !== 0 ? encoding13_8.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@bee/tree-pointer-0':
      return encoding0
    case '@bee/tree-pointer':
      return encoding1
    case '@bee/tree-delta':
      return encoding2
    case '@bee/cohort':
      return encoding3
    case '@bee/value-pointer':
      return encoding4
    case '@bee/block-pointer':
      return encoding5
    case '@bee/batch-pointer':
      return encoding6
    case '@bee/tree-0':
      return encoding7
    case '@bee/tree':
      return encoding8
    case '@bee/data':
      return encoding9
    case '@bee/key':
      return encoding10
    case '@bee/core':
      return encoding11
    case '@bee/block-0':
      return encoding12
    case '@bee/block-1':
      return encoding13
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
